version: "3.7"

## 服務連線URL網站: xxx.52.87.154.44.nip.io

services:

  ## 使用者的Flask網站
  ## 服務都在名稱為flask的資料夾內
  flask-web:
    build: 
      context: flask/
      dockerfile: Dockerfile
    container_name: template_flask
    # restart: always
    environment:
      - APP_NAME=FlaskApp
      # 反向代理服務機制
      - VIRTUAL_HOST=web.54.160.106.29.nip.io
      - LETSENCRYPT_HOST=web.54.160.106.29.nip.io
      - LETSENCRYPT_EMAIL=jayger1132@gmail.com
      - VIRTUAL_PORT=80
    expose:
      - 80
    depends_on:
      - db
  
  ## 資料庫
  ## 資料庫型態是mysql
  db:
    image: docker.io/bitnami/mysql:8.0
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - MYSQL_ROOT_PASSWORD=tokio328
      - MYSQL_USER=jayger1132
      - MYSQL_PASSWORD=tokio328
      - MYSQL_DATABASE=youbike
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  ## 用Phpmyadmin做管理
  phpmyadmin:
    image: docker.io/bitnami/phpmyadmin:5
    environment:
      - DATABASE_ALLOW_NO_PASSWORD=false
      - PHPMYADMIN_ALLOW_ARBITRARY_SERVER=false
      - PHPMYADMIN_ALLOW_REMOTE_CONNECTIONS=yes
      - DATABASE_HOST=db
      - DATABASE_USER=jayger1132
      - DATABASE_PASSWORD=tokio328
      # 反向代理服務機制
      - VIRTUAL_HOST=phpmyadmin.54.160.106.29.nip.io
      - LETSENCRYPT_HOST=phpmyadmin.54.160.106.29.nip.io
      - LETSENCRYPT_EMAIL=jayger1132@gmail.com
      - VIRTUAL_PORT=8080
    expose:
      - '8080'
    depends_on:
      - db

  ## 用Adminer做管理
  adminer:
    image: adminer
    restart: always
    environment:
      # 反向代理服務機制
      - VIRTUAL_HOST=adminer.54.160.106.29.nip.io
      - LETSENCRYPT_HOST=adminer.54.160.106.29.nip.io
      - LETSENCRYPT_EMAIL=jayger1132@gmail.com
      - VIRTUAL_PORT=8080
    expose:
      - 8080
    depends_on:
      - db

volumes:
  mysql_data:
    driver: local